name: variant
version: 2.4.2
description: Roslin Variant Pipeline v2.4.2
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.6
      max: 2.0.6
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/roslin-cmo/1.9.10/cmo/
  toil:
    version: 3.17.0-MSK
    install-path: /ifs/work/pi/roslin-toil/3.17.0-MSK/toil/
  singularity:
    version: 2.5.1
    install-path: /opt/common/CentOS_6-dev/singularity/singularity-2.5.1/bin/singularity
test:
  root: /ifs/work/pi/roslin-test
  tempDir: /scratch  
  runArgs: --leader-node large --single-node
  env:
    TOIL_LSF_ARGS: '-S 1 '
build:
  buildImages: false
  installCore: true
  buildThreads: 4
  vagrantSize: 50GB
