name: variant
root: /juno/work/ci/roslin-pipelines/
version: 2.5.9
description: Roslin Variant Pipeline v2.5.9
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /fscratch
    - /ifs
    - /srv
    - /juno
env:
  TOIL_LSF_ARGS: '-S 1 -sla CMOPI -W 168:00'
  TMPDIR: '/fscratch'
  TMP: '/fscratch'
dependencies:
  core:
    version:
      min: 2.1.2
      max: 2.1.2
  cmo:
    version: 1.9.13
    source: github:https://github.com/mskcc/cmo
  singularity:
    version: 3.3.0
    source: path:/opt/local/singularity/3.3.0/bin/singularity
  toil:
    version: 3.19.0
    source: github:https://github.com/mskcc/toil
test:
  root: /juno/work/ci/roslin-test/
  data_path: /juno/work/pi/nikhil/roslin-test/roslin_variant_version_2.5.0_test_data.tar.gz
  data_url: https://s3.us-east-2.amazonaws.com/roslindata/roslin_variant_version_2.5.0_test_data.tar.gz
  batchsystem: LSF
  cwlBatchsystem: LSF
  useDocker: False
  dockerRegistry: None
  tempDir: /scratch
  runArgs: '--test-mode --on-success /juno/work/pi/nikhil/roslin-internal-services/roslin-done.py --on-fail /juno/work/pi/nikhil/roslin-internal-services/roslin-fail.py'
  env:
    TOIL_LSF_ARGS: '-S 1 -sla CMOPI'
build:
  buildDocker: False
  buildSingularity: True
  buildCache: /juno/work/pi/nikhil/build-cache
  dockerRegistry: 'mskcc'
  dockerPush: False
  useVagrant: False
  installCore: True
  buildThreads: 2
